version: '3'

services:

  app-node:
    build:
      context: app-node
    networks:
      - nodenet
    volumes:
      - ./app-node:/usr/src/app
    tty: true
    container_name: app-node
    
  mysql:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
    networks:
      - nodenet
    

networks:
  nodenet:
    driver: bridge